on: [push, pull_request]

name: Build

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          toolchain: stable
          override: true
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --verbose
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --verbose
      - uses: actions/upload-artifact@v1
        name: Archive production artifacts
        with:
          name: bin
          path: target/gw