# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          #          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
#      - uses: actions-rs/cargo@v1
#        name: Test
#        with:
#          use-cross: true
#          command: test
#          args: --target=${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
