on:
  release:
    types: [created]

name: Upload release artifacts

jobs:
  create-and-uplad-artifacts:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --verbose
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --verbose
      - name: Optimize
        run: strip target/release/gw
        if: matrix.os != 'windows-latest'

      - name: Upload Release Asset
        if: matrix.os != 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          #upload_url: ${{ jobs.create-release.steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: target/release/gw
          asset_name: gw-${{matrix.os}}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset win
        if: matrix.os != 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/gw.exe
          asset_name: gw-${{matrix.os}}.exe
          asset_content_type: application/octet-streamh
